In [2]:
import numpy as np

In [ ]:
# membuat vector i dengan elemen (1,0)
i = np.array([1, 0])
i

array([1, 0])

In [ ]:
# membuat vector y dengan elemen (0, 1)
j = np.array([0, 1])
j

array([0, 1])

In [ ]:
# membuktikan bahwa vector i dan j orthogonal
np.dot(i, j)

np.int64(0)

In [4]:
# membuat vector v dengan elemen (1,2)
v = np.array([1, 2])
v

array([1, 2])

In [5]:
# membuat vector w dengan elemen (2,-1)
w = np.array([2, -1])
w

array([ 2, -1])

In [6]:
# membuktikan bahwa vector v dan w orthogonal
np.dot(v, w)

np.int64(0)