## Vectors

In [ ]:
import numpy as np

In [ ]:
# vector x dengan ukuran 3x1
x = np.array([10, 2, 4])

In [ ]:
# menghitung panjang vector x
len(x)

3

In [ ]:
# mengetahui ukuran vector x
x.shape

(3,)

In [ ]:
# menampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [ ]:
# mengakses elemen pertama dari vector x
x[0]

np.int64(10)

In [ ]:
# menampilkan tipe data elem pertama dari vector x
type(x[0])

numpy.int64

## Vector Transpos

In [ ]:
# melakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([10,  2,  4])

In [ ]:
# mengetahui ukuran transpose vector x
x_t.shape

(3,)

In [ ]:
# Vector y dengan ukuran 3 x 1
y = np.array([[30, 3, 5]])
y

array([[30,  3,  5]])

In [ ]:
# mengetahui ukuran vector y
y.shape

(1, 3)

In [ ]:
# melakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[30],
       [ 3],
       [ 5]])

In [ ]:
# mengetahui ukuran transpose vector y
y_t.shape

(3, 1)

## pytorch dan tensorflow

In [ ]:
import torch
import tensorflow as tf

In [ ]:
# menampilkan vector x dalam variable x_pt
x_pt = torch.tensor([10, 2, 4])
x_pt

tensor([10,  2,  4])

In [ ]:
# menampilkan ukuran dari vector x_pt
x_pt.shape

torch.Size([3])

In [ ]:
# menampilkan vector y dalam variable y_pt
y_pt = torch.tensor([30, 3, 5])
y_pt

tensor([30,  3,  5])

In [ ]:
# menampilkan ukuran dari vector y_pt
y_pt.shape

torch.Size([3])